/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-20-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   07-20-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public inherited sharing class Google_sortNumbers {
    /**
     * * Approach #1: Using Dutch National Flag Algorithm
     * 1. Use three variables - low, mid & high.
     * 2. Use iteration so that mid < high.
     * 3. If mid is 0, swap with low & increment both by 1.
     * 4. If mid is 1, increment m by 1.
     * 5. If mid is 2, swap with high & decrement high by 1.
     */
    public List<Integer> sortNumber(List<Integer> stream){

    }
}
